### ISSUE TITLE
6 errors when compiled with LLVM

### ISSUE THREAD

**Issue by jbwyatt4** [eudoxia0/corvus#3]
Hello I got the following message when I tried to build Hylas. My system is Ubuntu 13.04 64bit and I built my own LLVM 3.3 binaries.
# Compile the helper Hylas<->LLVM interface

`(which clang++; which g++) | head -n 1` src/jit.cpp -o libhylas.o -c -fPIC -Wall -Wextra -Werror  -std=c++0x -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS
src/jit.cpp:87:20: error: reference to 'error_code' is ambiguous
            return error_code("ERROR: Couldn't find program entry point.");
                   ^
src/jit.cpp:48:11: note: candidate found by name lookup is 'error_code'
    Code\* error_code(const char\* desc) {
          ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate found by
      name lookup is 'llvm::error_code'
class error_code {
      ^
src/jit.cpp:87:20: error: no matching conversion for functional-style cast from
      'const char [42]' to 'llvm::error_code'
            return error_code("ERROR: Couldn't find program entry point.");
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'const char [42]' to 'const llvm::error_code' for 1st
      argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'const char [42]' to 'llvm::error_code' for 1st argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:740:3: note: candidate template
      ignored: substitution failure [with E = const char _]: no type named
      'type' in 'llvm::enable_if_c<false, void>'
  error_code(E _e, typename enable_if_c<
  ^
/usr/local/include/llvm/Support/system_error.h:730:3: note: candidate
      constructor not viable: requires 0 arguments, but 1 was provided
  error_code() : _val_(0), _cat_(&system_category()) {}
  ^
/usr/local/include/llvm/Support/system_error.h:736:3: note: candidate
      constructor not viable: requires 2 arguments, but 1 was provided
  error_code(int _val, const error_category& _cat)
  ^
src/jit.cpp:91:20: error: reference to 'error_code' is ambiguous
            return error_code(errors.getMessage().data());
                   ^
src/jit.cpp:48:11: note: candidate found by name lookup is 'error_code'
    Code_ error_code(const char\* desc) {
          ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate found by
      name lookup is 'llvm::error_code'
class error_code {
      ^
src/jit.cpp:91:20: error: no matching conversion for functional-style cast from
      'const char _' to 'llvm::error_code'
            return error_code(errors.getMessage().data());
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'const char *' to 'const llvm::error_code' for 1st
      argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'const char *' to 'llvm::error_code' for 1st argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:740:3: note: candidate template
      ignored: substitution failure [with E = const char *]: no type named
      'type' in 'llvm::enable_if_c<false, void>'
  error_code(E _e, typename enable_if_c<
  ^
/usr/local/include/llvm/Support/system_error.h:730:3: note: candidate
      constructor not viable: requires 0 arguments, but 1 was provided
  error_code() : _val_(0), _cat_(&system_category()) {}
  ^
/usr/local/include/llvm/Support/system_error.h:736:3: note: candidate
      constructor not viable: requires 2 arguments, but 1 was provided
  error_code(int _val, const error_category& _cat)
  ^
src/jit.cpp:95:20: error: reference to 'error_code' is ambiguous
            return error_code(parser_errors.data());
                   ^
src/jit.cpp:48:11: note: candidate found by name lookup is 'error_code'
    Code_ error_code(const char\* desc) {
          ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate found by
      name lookup is 'llvm::error_code'
class error_code {
      ^
src/jit.cpp:95:20: error: no matching conversion for functional-style cast from
      'const char _' to 'llvm::error_code'
            return error_code(parser_errors.data());
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'const char *' to 'const llvm::error_code' for 1st
      argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:726:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'const char *' to 'llvm::error_code' for 1st argument
class error_code {
      ^
/usr/local/include/llvm/Support/system_error.h:740:3: note: candidate template
      ignored: substitution failure [with E = const char *]: no type named
      'type' in 'llvm::enable_if_c<false, void>'
  error_code(E _e, typename enable_if_c<
  ^
/usr/local/include/llvm/Support/system_error.h:730:3: note: candidate
      constructor not viable: requires 0 arguments, but 1 was provided
  error_code() : _val_(0), _cat_(&system_category()) {}
  ^
/usr/local/include/llvm/Support/system_error.h:736:3: note: candidate
      constructor not viable: requires 2 arguments, but 1 was provided
  error_code(int _val, const error_category& _cat)
  ^
6 errors generated.
make: *_\* [backend] Error 1

**Comment by jbwyatt4** [comment]
It looks like all the errors are due to a conflict between Hylas's error_code function and LLVM's. A simple rename may fix it.

**Comment by eudoxia0** [comment]
I tried compiling this on an Arch VM (Getting an up-to-date Clang on Ubuntu is impossible) with LLVM 3.3 and it worked just fine. Just to be sure I'll add a name prefix to make sure nothing collides.

**Comment by jbwyatt4** [comment]
Let me know-l'lI test it again.
